name: example
description: A new Flutter application.
# Paste just below 'description:'

version: 0.0.2

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  after_layout: ^1.0.7+2
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_db_input_widget:
    path: ../
  flutter_theme_package:
    git:
      url: https://github.com/GitHubStuff/flutter_theme_package.git
  flutter_tracers:
    git:
      url: https://github.com/GitHubStuff/flutter_tracers.git
  notifier: ^1.0.2
  shared_preferences: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
