name: flutter_db_input_widget
description: A Widget for flutter_db_builder
version: 0.0.2+3
homepage: https://github.com/GitHubStuff/flutter_db_input_widget

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  after_layout: ^1.0.7+2
  auto_size_text: ^2.1.0
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  flutter_sqlite_controller:
    git:
      url: https://github.com/GitHubStuff/flutter_sqlite_controller.git
  flutter_strings:
    git:
      url: https://github.com/GitHubStuff/flutter_strings.git
  flutter_theme_package:
    git:
      url: https://github.com/GitHubStuff/flutter_theme_package.git
  flutter_tracers:
    git:
      url: https://github.com/GitHubStuff/flutter_tracers.git
  intl: ^0.16.1
  path: ^1.6.4
  shared_preferences: ^0.5.6+1
  sqflite: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
