name: example_db_input_widget
description: Crude editor for creating SQLite objects


version: 0.1.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  after_layout: ^1.0.7+2
  auto_size_text: ^2.1.0
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  flutter_db_input_widget:
    path: ../
  flutter_theme_package:
    git:
      url: https://github.com/GitHubStuff/flutter_theme_package.git
  flutter_tracers:
    git:
      url: https://github.com/GitHubStuff/flutter_tracers.git
  keyboard_visibility: ^0.5.6
  path: ^1.6.4
  shared_preferences: ^0.5.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
