import 'package:flutter/material.dart';

/// This class holds the information about a given input row, it can be the initial value provided
/// for TabletInputLine columns, or the data generated by TabletInputLine and sent back via a stream.
class FieldInfo {
  static const _DataTypes = {'a', 'b', 'c', 'd', 'i', 'r', 's'};
  static bool isDataTypes(String type) => _DataTypes.contains(type);
  static bool isComplex(String type) => (type == 'a' || type == 'c');

  List<String> _items;
  final List<String> fields;
  bool tabbedOut = false;
  String get field => _items[0];
  String get json => _items[1];
  String get type => _items[2];
  String get table => (type == 'a' || type == 'c') ? _items[3] : null;
  String get comment => _items[4];

  FieldInfo({this.fields = const ['Field', 'Json', 'a,b,c,d,i,r,s', 'Table', 'Comment']})
      : assert(fields != null && fields.length > 0) {
    _items = List.filled(fields.length, '');
  }
  void mock({bool complex = false}) {
    _items = List();
    _items.add('field');
    _items.add('json');
    _items.add(complex == true ? 'c' : 'i');
    _items.add('table');
    _items.add('comment');
  }

  setIndex(int index, {@required String string}) {
    assert(index != null && index >= 0 && index < _items.length, '$index is invalid for size ${_items.length}');
    assert(string != null);
    final chr = string.runes.toList().last;
    if (chr == 9) string = string.substring(0, string.length - 1);
    _items[index] = string;
  }

  String validate() {
    if (field.isEmpty) return 'Empty Field';
    if (json.isEmpty) return 'Empty Json';
    if (!isDataTypes(type)) return 'Invalid Type';
    if (isComplex(type) && table?.isEmpty == true) return 'Missing table for type $type';
    if (!isComplex(type) && table != null) return 'Table for type $type';
    return null;
  }
}
